name: Publish build to Sonatype

on:
  push:
    tags:
      - '*'
  repository_dispatch:
    types: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'johnsonlee'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: publish to sonatype
      run: |
        echo "Release version ${GITHUB_REF/refs\/tags\/v/} ..."
        echo "Create GPG private key"
        echo $GPG_KEY_ARMOR | base64 --decode > ${GITHUB_WORKSPACE}/secring.gpg
        ./gradlew initializeSonatypeStagingRepository -S --no-daemon -Pversion=${GITHUB_REF/refs\/tags\/v/}
        ./gradlew -p core publishToSonatype -S --no-daemon \
            -Pversion=${GITHUB_REF/refs\/tags\/v/} \
            -Psigning.keyId=${GPG_KEY_ID} \
            -Psigning.password=${GPG_PASSPHRASE} \
            -Psigning.secretKeyRingFile=${GITHUB_WORKSPACE}/secring.gpg
        ./gradlew -p compiler publishToSonatype -S --no-daemon \
            -Pversion=${GITHUB_REF/refs\/tags\/v/} \
            -Psigning.keyId=${GPG_KEY_ID} \
            -Psigning.password=${GPG_PASSPHRASE} \
            -Psigning.secretKeyRingFile=${GITHUB_WORKSPACE}/secring.gpg
        ./gradlew -p runtime publishReleasePublicationToSonatypeRepository -S --no-daemon \
            -Pversion=${GITHUB_REF/refs\/tags\/v/} \
            -Psigning.keyId=${GPG_KEY_ID} \
            -Psigning.password=${GPG_PASSPHRASE} \
            -Psigning.secretKeyRingFile=${GITHUB_WORKSPACE}/secring.gpg
        ./gradlew closeAndReleaseRepository -S --no-daemon -Pversion=${GITHUB_REF/refs\/tags\/v/}
      env:
        JAVA_OPTS: -Xmx8g -XX:MetaspaceSize=1g -Dfile.encoding=UTF-8
        JVM_OPTS:  -Xmx8g -XX:MetaspaceSize=1g -Dfile.encoding=UTF-8
        GPG_KEY_ARMOR: ${{ secrets.GPG_KEY_ARMOR }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PACKAGE_GROUP: ${{ secrets.OSSRH_PACKAGE_GROUP }}